easy_admin:
  site_name: 'Locataire A Propri√©taire - Administration'
  design:
    assets:
      css: ['assets/css/admin/easyadmin.css']
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'