easy_admin:
  design:
    menu:
      - {entity: 'User'}
      - {entity: 'Homepage'}
      - label: 'Les programmes'
        children:
          - {entity: 'Program', label: 'Biens'}
          - {entity: 'MainCriteria'}
          - {entity: 'Criteria'}
          - {entity: 'Filter'}
          - {entity: 'ProgramPicture', label: 'Image des biens'}

      - {label: 'DÃ©connexion', route: 'fos_user_security_logout'}